name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        description: The tag name of the release.
        required: false
        type: string

jobs:
  deploy:
    # Make sure the pull request is merged or if the input is not empty.
    if: ${{ github.event.pull_request.merged }} || ${{ github.event.inputs.tag }}
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      # Install our dependencies if we did not restore a dependency cache.
      - name: Install dependencies using yarn
        run: yarn --frozen-lockfile --prefer-offline

      - name: Build the project
        run: yarn build

      - name: Zip the project's bundle
        uses: papeloto/action-zip@v1
        with:
          files: .output/
          dest: output.zip

      # Parse the tag using the regex `v[0-9].*`.
      - name: Parse the release tag
        id: release
        run: |
          echo "::set-output name=tag::$(grep 'v[0-9].*' <<< \
          '${{ github.head_ref }} ${{ github.event.inputs.tag }}')"

      - name: Create the release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.release.outputs.tag }}
        with:
          tag_name: ${{ steps.release.outputs.tag }}
          generate_release_notes: true
          files: dist.zip
